name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set YARN_IGNORE_NODE
        run: echo "YARN_IGNORE_NODE=1" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Vitest tests
        run: yarn run test:run -- --coverage

      - name: Run Storybook tests
        run: yarn run storybook:test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
